name: Build / Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: excape/wedding-website/wedding-website
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PKG_PASSWORD }}
          registry: docker.pkg.github.com
